### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by Rhoose-M8** [ArtemHrytsenko04/Agile-Projects-Iteartion1-#2]
# Task List

___
Iteration One:
- [x] ITERATION ONE COMPLETE AND MARKED
___
Iteration Two:
- [x] Complete meeting minutes two document
- [x] download resource needs document
- [x] complete resource needs document
- [x] upload resource needs document
- [x] download gantt chart document
- [x] Complete progress report two
- [x] Upload progress report two
- [x] Upload meeting minutes 2
- [x] upload gantt chart
- [x] update git boards
- [x] Update Gantt chart
- [x] ITERATION TWO COMPLETE AND MARKED

____
Iteration Three: 
- [x] Start research for iteration 3
- [x] Source templates for risk register, user acceptance testing, meeting minutes, progress report 3
- [x] Source documents required for web hosting
- [x] Upload documents for web hosting
- [x] Complete risk register
- [x] Upload risk register
- [x] Complete user acceptance testing
- [x] Upload user acceptance testing
- [x] complete and upload meeting minutes 3
- [x] complete and upload progress report 3
- [ ] check iteration 3 work for quality
- [ ] check iteration 2 work for quality
- [x] check iteration 1 work for quality
- [x] update README with relevant links
- [x] ensure all files are in correct places
- [x] ensure github is public so that Noor can access for marking
- [x] **UPDATE LINK TO USER ACCEPTANCE TESTING**
- [ ] ITERATION THREE COMPLETE AND MARKED

**Comment by Rhoose-M8** [comment]
Hi mate,
I have updated this to include all tasks for iteration 3. I will update as I go along

**Comment by Rhoose-M8** [comment]
Hi mate,
All documents are now uploaded to github.
I have updated the readme with links to their respective files.
We should go through and triple check all of our work before handover.
Cheers! :)
